/*
 * UART_Cfg.h
 *
 *  Created on: Jul 17, 2023
 *      Author: mazen
 */

#ifndef INCLUDE_MCAL_UART_UART_CFG_H_
#define INCLUDE_MCAL_UART_UART_CFG_H_

#define F_CPU 	  8000000UL
#define BAUDRATE  9600

#define TX_INTERRUPT_ENABLE				 INTERRUPT_DISABLE
#define RX_INTERRUPT_ENABLE				 INTERRUPT_DISABLE
#define DATA_REG_EMPTY_INTERRUPT_ENABLE  INTERRUPT_DISABLE

#define CHARACTER_SIZE  EIGHT_BITS

#define NON_BLOCKING_TIME_OUT 5000
#define NO_VALUE_RETURNED 255


#endif /* INCLUDE_MCAL_UART_UART_CFG_H_ */
